#!/usr/bin/env python3
"""Generate traceability.md (REQ -> module -> spec FR -> test cases -> tasks) from the documentation set.

Usage: python3 scripts/traceability.py [project_root] [output_file]     (defaults: ".", "<root>/traceability.md")
Conventions it relies on (see SKILL.md):
  requirement.md      table rows starting with "| REQ-001 | <text> |"
  modules/*/specification.md   FR table rows starting with "| XXX-FR-01 | ... REQ-001 ..."
  modules/*/test-case.md       rows starting with "| XXX-TC-001 | ... [REQ-001] ..."
  task.md             lines containing "**XXX-T01**" and REQ ids
Exits with status 1 and lists gaps if any REQ lacks an owning FR, a test case or a task.
"""
import collections
import glob
import os
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else "."
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, "traceability.md")
read = lambda p: open(os.path.join(root, p), encoding="utf-8").read()

reqs = re.findall(r"^\| (REQ-\d+) \| (.+?) \|\s*$", read("requirement.md"), re.M)
modules = sorted(os.path.basename(os.path.dirname(p)) for p in glob.glob(os.path.join(root, "modules", "*", "specification.md")))

fr = collections.defaultdict(lambda: collections.defaultdict(set))
tc = collections.defaultdict(lambda: collections.defaultdict(list))
tasks = collections.defaultdict(list)
for m in modules:
    for line in open(os.path.join(root, "modules", m, "specification.md"), encoding="utf-8"):
        row = re.match(r"\|\s*\**([A-Z]+-FR-\d+)", line)
        if row:
            for q in set(re.findall(r"REQ-\d+", line)):
                fr[q][m].add(row.group(1))
    tc_path = os.path.join(root, "modules", m, "test-case.md")
    if os.path.exists(tc_path):
        for line in open(tc_path, encoding="utf-8"):
            row = re.match(r"\| ([A-Z]+-TC-\d+) \|", line)
            if row:
                for q in set(re.findall(r"REQ-\d+", line)):
                    tc[q][m].append(row.group(1))
for line in read("task.md").splitlines():
    row = re.search(r"\*\*([A-Z]+-T\d+)\*\*", line)
    if row:
        for q in set(re.findall(r"REQ-\d+", line)):
            tasks[q].append(row.group(1))


def span(ids):
    ids = sorted(ids)
    return ", ".join(ids) if len(ids) <= 4 else f"{ids[0]} … {ids[-1]} ({len(ids)})"


lines = ["# Traceability Matrix", "",
         "Requirement → Module → Specification → Test Case → Implementation Task. Generated by `scripts/traceability.py`; do not edit by hand.", "",
         "| REQ | Requirement | Owning module | Spec FR IDs | Test cases | Other modules (test cases) | Tasks |", "|---|---|---|---|---|---|---|"]
gaps = []
for q, text in reqs:
    owner = max(modules, key=lambda m: len(fr[q][m])) if any(fr[q].values()) else None
    f = span(fr[q][owner]) if owner else "—"
    c = span(tc[q][owner]) if owner and tc[q][owner] else "—"
    other = "; ".join(f"{m}: {len(v)}" for m, v in tc[q].items() if m != owner) or "—"
    t = span(tasks[q]) if tasks[q] else "—"
    if not owner or c == "—" or t == "—":
        gaps.append(q)
    lines.append(f"| {q} | {text.replace('|', '/')[:90]} | {owner or '—'} | {f} | {c} | {other} | {t} |")
lines += ["", "## Coverage", "",
          f"- Requirements: {len(reqs)}. " + ("All have an owning module, a test case and a task." if not gaps else f"Gaps: {', '.join(gaps)}")]
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"{len(reqs)} requirements, gaps: {gaps or 'none'} -> {out}")
sys.exit(1 if gaps else 0)
